import { CollectionType, ProcessingState } from "./types";
export declare const SurtPrefixRegex: RegExp;
export declare const SurtFullRegex: RegExp;
export declare const BoolDisplayMap: Record<string, string>;
export declare const EventTypeDisplayMap: Record<ProcessingState, string>;
export declare const CollectionTypeDisplayMap: Record<CollectionType, string>;
export declare const UrlCollectionParamName = "cid";
export declare const UrlCollectionsParamName = "cid[]";
export declare const DefaultSelectElementPromptText = "Please select...";
export declare const NewHelpTicketUrl = "https://arch-webservices.zendesk.com/hc/en-us/requests/new";
