# Generated by Django 4.2.16 on 2025-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0017_collection_description_collection_info_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcategory",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
