# Generated by Django 4.2.16 on 2025-10-14 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0020_fix_jobcategory_id_seq"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionUserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opt_out", models.BooleanField(blank=True, default=False)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usersettings_set",
                        to="keystone.collection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="collectionusersettings",
            constraint=models.UniqueConstraint(
                fields=("collection", "user"), name="collectionusersettings_unique"
            ),
        ),
    ]
