# Generated by Django 4.2.16 on 2025-11-04 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0021_collectionusersettings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetUserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opt_out", models.BooleanField(blank=True, default=False)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usersettings_set",
                        to="keystone.dataset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="datasetusersettings",
            constraint=models.UniqueConstraint(
                fields=("dataset", "user"), name="datasetusersettings_unique"
            ),
        ),
    ]
