# Generated by Django 4.2.16 on 2025-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0022_share_global_datasets_via_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("STAFF", "Staff"),
                    ("SUBSCRIBER", "Subscriber"),
                    ("TRIAL", "Trial"),
                ],
                default="TRIAL",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("type", "STAFF"),
                    ("type", "SUBSCRIBER"),
                    ("type", "TRIAL"),
                    _connector="OR",
                ),
                name="check_valid_type",
            ),
        ),
    ]
