# Generated by Django 4.2.16 on 2025-11-20 20:48

from django.db import migrations, models


def wayback_collections_size_bytes_setter(size_bytes):
    def f(apps, schema_editor):
        """Set the size_bytes of all wayback-type collections to the
        specified value.
        """
        queryset = apps.get_model("keystone", "Collection").objects.filter(
            metadata__input_spec__type="wayback"
        )
        ids = set(queryset.values_list("id", flat=True))
        queryset.update(size_bytes=size_bytes)
        print(
            f"\n  - Set size_bytes={size_bytes} on the following {len(ids)} Wayback-type "
            f"collection IDs: {ids}"
        )

    return f


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0024_datasetusersettings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="size_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobstart",
            name="input_bytes",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.RunPython(
            code=wayback_collections_size_bytes_setter(None),
            reverse_code=wayback_collections_size_bytes_setter(0),
        ),
    ]
