# Generated by Django 4.2.16 on 2026-01-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0025_alter_collection_size_bytes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("change_role", "Can change user roles"),
                    ("create_custom_collection", "Create Custom Collection"),
                    ("generate_dataset", "Generate Dataset"),
                    ("create_notebook", "Create Notebook"),
                ]
            },
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="check_valid_role",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "User"), ("VIEWER", "Viewer")],
                default="USER",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("role", "ADMIN"),
                    ("role", "USER"),
                    ("role", "VIEWER"),
                    _connector="OR",
                ),
                name="check_valid_role",
            ),
        ),
    ]
