# Generated by Django 4.2.16 on 2026-02-17 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0026_alter_user_options_remove_user_check_valid_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("change_role", "Can change user roles"),
                    ("create_custom_collection", "Create Custom Collection"),
                    ("generate_dataset", "Generate Dataset"),
                    ("list_account_users", "List Account Users"),
                    ("add_account_user", "Add Account User"),
                    ("change_account_user", "Change Account User"),
                    ("list_account_teams", "List Account Teams"),
                    ("add_account_team", "Add Account Team"),
                    ("change_account_team", "Change Account Team"),
                    ("admin_account", "Administer Account"),
                ]
            },
        ),
    ]
