export * from "./webservices/src/lib/helpers";

export { createElement } from "./webservices/src/legacy/lib/domLib";
import { createElement } from "./webservices/src/legacy/lib/domLib";
import { humanBytes } from "./webservices/src/lib/helpers";

import {
  SurtFullRegex,
  SurtPrefixRegex,
  UrlCollectionParamName,
  UrlCollectionsParamName,
} from "./constants";
import {
  Collection,
  CollectionType,
  Dataset,
  ProcessingState,
  SpecialCollectionMetadata,
} from "./types";

export const identity = <T>(x: T) => x;

export const Paths = {
  collection: (id: Collection["id"]) => `/collections/${id}`,

  collections: `/collections`,

  dataset: (id: Dataset["id"]) => `/datasets/${id}`,

  datasets: `/datasets`,

  generateCollectionDataset: (collectionId: Collection["id"]) =>
    `/datasets/generate?${UrlCollectionParamName}=${collectionId}`,

  buildSubCollection: (sourceCollectionIds?: Array<Collection["id"]>) =>
    sourceCollectionIds === undefined
      ? "/collections/custom-collection-builder"
      : `/collections/custom-collection-builder?${sourceCollectionIds
          .map((x) => `${UrlCollectionsParamName}=${x}`)
          .join("&")}`,

  teams: "/account/teams",
};

export function isActiveProcessingState(state: ProcessingState): boolean {
  return (
    state === ProcessingState.SUBMITTED ||
    state === ProcessingState.QUEUED ||
    state === ProcessingState.RUNNING
  );
}

export function timestampStringToYearMonthString(timestamp: string): string {
  const date = new Date(timestamp);
  const formattedDate = date.toLocaleString("default", {
    month: "short",
    year: "numeric",
  }); // eg. "Sep 2005"

  return formattedDate;
}

export function readableFacetName(facetName: string, facetField: string) {
  // convert camelcase name into a more readable form for f_organizationType field - eg. 'collegesAndUniversities' --> 'Colleges And Universities'
  if (facetField === "f_organizationType") {
    const nameWordsSeparated = facetName.split(/(?=[A-Z])/); // split on capital letter
    return nameWordsSeparated
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" "); // capitalize each word and join with spaces
  } else {
    return facetName;
  }
}

export function isValidCustomInputCollection(collection: Collection): boolean {
  /**
   * Return a bool indicating whether the specified collection can be used as a
   * custom collection input.
   */
  return (
    collection.collection_type === CollectionType.AIT ||
    collection.collection_type === CollectionType.CUSTOM ||
    (collection.collection_type === CollectionType.SPECIAL &&
      !(collection.metadata as SpecialCollectionMetadata)?.input_spec)
  );
}

export function formatCollectionSize(
  collection: Collection
): HTMLElement | string {
  /**
   * Return a <span> displaying "n/a" w/ title for zero-byte SPECIAL-type collections,
   or a human formatted byte size string otherwise.
   */
  return collection.size_bytes === 0 &&
    collection.collection_type === CollectionType.SPECIAL
    ? createElement("span", {
        textContent: "n/a",
        title:
          "A size value is not currently available for this collection type",
        style: "cursor: not-allowed;",
      })
    : humanBytes(collection.size_bytes, 1);
}

type SurtCheck = {
  isValid: boolean;
  isPrefix: boolean;
  match: null | RegExpExecArray;
};

export function checkSurt(s: string): SurtCheck {
  // Return a tuple in the form [<isValid>, <isPrefix>]
  let match = SurtPrefixRegex.exec(s);
  if (match !== null) {
    return { isValid: true, isPrefix: true, match };
  }
  match = SurtFullRegex.exec(s);
  if (match !== null) {
    return { isValid: true, isPrefix: false, match };
  }
  return { isValid: false, isPrefix: false, match };
}

function makeSurt(
  hostname: string,
  port: string,
  username: string,
  password: string,
  pathEtc: string
): string {
  /*
   * Generate a SURT from parts.
   */
  const parts = [hostname.split(".").reverse().join(","), ","];
  if (port) {
    parts.push(`:${port}`);
  }
  if (username) {
    parts.push(`@${username}`);
    if (password) {
      parts.push(`:${password}`);
    }
  }
  // If no port or username was specified, or pathEtc is non-empty,
  // adopt an impled SURT prefix form, otherwise adopt the non-prefix form.
  if (port || username || pathEtc) {
    // Remove the trailing domain part comma and add closing paren.
    parts.splice(1, 1);
    parts.push(")");
    // Maybe append pathEtc.
    if (pathEtc && pathEtc !== "/") {
      const slash = pathEtc.startsWith("/") ? "" : "/";
      parts.push(`${slash}${pathEtc}`);
    }
  }
  const surt = parts.join("").toLowerCase();
  if (!checkSurt(surt).isValid) {
    console.warn(`checkSurt failed value generated by urlToSurt: "${surt}"`);
  }
  return surt;
}

function urlToMakeSurtArgs(
  urlStr: string
): [string, string, string, string, string] {
  const url = new URL(urlStr);
  // Ensure that pathEtc includes a leading slash if urlStr included one.
  const slash = urlStr.split("/").length > 3 ? "/" : "";
  // Note that URL() will set pathname to "/" if no path, only search params etc,
  // are specified, so this slice() will always work / include said search params.
  const pathEtc = `${slash}${url.href.split("/").slice(3).join("/")}`;
  let hostname = url.hostname;
  // URL() allows a trailing "." in the hostname, but that's not ok for SURT purposes.
  if (hostname.endsWith(".")) {
    hostname = url.hostname.slice(0, -1);
  }
  // Drop any "www." hostname prefix.
  if (hostname.startsWith("www.")) {
    hostname = hostname.slice(4);
  }
  return [hostname, url.port, url.username, url.password, pathEtc];
}

export function urlToSurt(urlStr: string): string {
  // http://crawler.archive.org/apidocs/org/archive/util/SURT.html
  const [hostname, port, username, password, pathEtc] =
    urlToMakeSurtArgs(urlStr);
  return makeSurt(hostname, port, username, password, pathEtc);
}

export function assertIsValidWildcardPatternUrl(url: URL): boolean {
  /*
   * Throw an Error if the URL specifies an unsupported wildcard pattern.
   */
  // Reject hostname wildcards.
  if (url.hostname.includes("%2A")) {
    throw new Error("Hostname wildcards are not supported");
  }
  if (
    (url.pathname.includes("*") &&
      (url.pathname.split("*").length > 2 ||
        url.pathname.slice(-1) !== "*" ||
        url.pathname.slice(-2) === "/*")) ||
    url.search.includes("*") ||
    url.hash.includes("*")
  ) {
    throw new Error(
      "URL pathname can include at most one trailing wildcard (*) character, and only in the absence of '?' and '#' characters"
    );
  }
  return true;
}

export function urlToExpandedSurts(urlStr: string): Array<string> {
  // http://crawler.archive.org/apidocs/org/archive/util/SURT.html
  const [hostname, port, username, password, pathEtc] =
    urlToMakeSurtArgs(urlStr);
  const surts: Array<string> = [];
  const ports = port ? [port] : [port, "80", "443"];

  const isPrefix =
    assertIsValidWildcardPatternUrl(new URL(urlStr)) && pathEtc.endsWith("*");
  const finalPathEtc = isPrefix ? pathEtc.slice(0, -1) : pathEtc;

  const pathSuffixes =
    !finalPathEtc || finalPathEtc.endsWith("/") || isPrefix
      ? [""]
      : finalPathEtc.includes("?") || finalPathEtc.includes("#")
      ? [" "]
      : [" ", "/", "?", "#"];
  for (const p of ports) {
    for (const pathSuffix of pathSuffixes) {
      surts.push(
        makeSurt(
          hostname,
          p,
          username,
          password,
          `${finalPathEtc}${pathSuffix}`
        )
      );
    }
  }
  surts.sort();
  return surts;
}

type SurtFullRegexMatchGroups = {
  domain: string;
  port: undefined | string;
  userinfo: undefined | string;
  pathname: string;
};

export function surtToUrl(s: string): string | null {
  const surtCheck = checkSurt(s);
  if (!surtCheck.isValid) {
    console.warn(`Not a valid SURT: "${s}"`);
    return null;
  }
  // There is no valid URL transform for prefix-type SURTs.
  if (surtCheck.isPrefix) {
    return null;
  }
  if (!surtCheck.match) {
    console.warn(`Could not parse SURT: "${s}"`);
    return null;
  }
  const groups = surtCheck.match.groups as SurtFullRegexMatchGroups;
  const parts = ["http://"];
  if (groups.userinfo) {
    parts.push(`${groups.userinfo}@`);
  }
  parts.push(groups.domain.split(",").reverse().join("."));
  if (groups.port) {
    parts.push(`:${groups.port}`);
  }
  parts.push(groups.pathname);
  return parts.join("");
}
